# Generated by Django 2.2.6 on 2019-10-26 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(30, 'small 30cm'), (50, 'medium 50cm')], default=30)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.TextField()),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza_app.Pizza')),
            ],
        ),
    ]
