# Generated by Django 2.2.6 on 2019-10-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
        ('pizza_order_app', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pizza_flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pizza_app.PizzaFlavor'),
        ),
    ]
